In [26]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from io import StringIO


# set pandas display options
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [28]:
# Set the path to the data
data_dir = Path('../../models/hotels')

# def load_data(data_dir):
#     dfs = []
#     for model_dir in data_dir.iterdir():
#         if model_dir.is_dir():
#             model = model_dir.name

#             seed = re.search(r'_s(\d+)', model)
#             if seed:
#                 seed = int(seed.group(1))
#             else:
#                 seed = 0
            
#             # strip the seed from the model name
#             model = re.sub(r'_s\d+', '', model)

#             print(model, seed)
            
#             if (model_dir / 'inference' / 'eval_result.txt').exists():
#                 results_file = model_dir / 'inference' / 'eval_result.txt'
#             elif (model_dir / 'eval_result.txt').exists():
#                 results_file = model_dir / 'eval_result.txt'

#             else:
#                 print(f'No results in {model_dir}')
#                 continue
                
#             with open(results_file, 'r', encoding='utf8') as f:
#                 file_contents = [line.strip() for line in f.readlines()]
                
#                 print(len(file_contents))
#                 if len(file_contents) == 4:
#                     print('skipping first line')
#                     file_contents = file_contents[1:]

#                 csv_string = StringIO('\n'.join(file_contents))
#                 df = pd.read_csv(csv_string, sep=",", header=0)
                
#                 # rename Unnamed: 0 to file
#                 df.rename(columns={'Unnamed: 0': 'file'}, inplace=True)

#                 df['model'] = model
#                 df['seed'] = seed

#                 # put the model and seed columns first
#                 cols = df.columns.tolist()
#                 cols = cols[-2:] + cols[:-2]
#                 df = df[cols]

#                 dfs.append(df)

#     df = pd.concat(dfs)
#     return df

def load_data(data_dir):
    dfs = []
    for model_dir in data_dir.iterdir():
        if model_dir.is_dir():
            model = model_dir.name

            seed = re.search(r'_s(\d+)', model)
            if seed:
                seed = int(seed.group(1))
            else:
                seed = 0
            
            # strip the seed from the model name
            model = re.sub(r'_s\d+', '', model)

            print(model, seed)
            
            if (model_dir / 'eval_result.txt').exists():
                results_file = model_dir / 'eval_result.txt'

            else:
                print(f'No results in {model_dir}')
                continue
                
            df = pd.read_csv(results_file, sep=",", header=0)
            
            # rename Unnamed: 0 to file
            df.rename(columns={'Unnamed: 0': 'file'}, inplace=True)

            df['model'] = model
            df['seed'] = seed

            # put the model and seed columns first
            cols = df.columns.tolist()
            cols = cols[-2:] + cols[:-2]
            df = df[cols]

            dfs.append(df)

    df = pd.concat(dfs)
    return df

df = load_data(data_dir)
print(df.columns)
df
df.to_csv('hotel_results.csv', index=False)

baseline 0
baseline 42
baseline 985
filt_freq_distro 0
filt_freq_distro 42
filt_freq_distro 985
filt_gen_sent 0
filt_gen_sent 42
filt_gen_sent 985
filt_rrsts 0
No results in ../../models/hotels/filt_rrsts
filt_rrtfidf 0
No results in ../../models/hotels/filt_rrtfidf
filt_tfidf 0
No results in ../../models/hotels/filt_tfidf
filt_tgt_ppl 0
filt_combo 0
filt_tgt_ppl_abl_20 0
filt_tgt_ppl_abl_60 0
filt_tgt_ppl_abl_80 0
filt_tgt_ppl 42
filt_tgt_ppl 985
rule_based 0
label_tgt_ppl 0
No results in ../../models/hotels/label_tgt_ppl
ground_truth 0
Index(['model', 'seed', 'file', 'test set size', 'BLEU', 'ROUGE-1', 'ROUGE-2', 'ROUGE-L', 'METEOR', 'SARI-BP', 'SARI', 'CHRF-tgt', 'CHRF-src', 'intraDIST-1', 'intraDIST-2', 'interDIST-1', 'interDIST-2', 'Self-BLEU', 'Uniq', 'rep-r', 'rep-w', 'seq-rep-n', 'paraphrase_reps', 'src-tgt sts', 'domain acc', 'rating acc', 'source acc', 'hyp lens'], dtype='object')

In [4]:
# compute the mean and std of metrics across seeds

agg_df = df[df['model'].isin(['baseline', 'filt_tgt_ppl', 'filt_gen_sent', 'filt_freq_distro'])].groupby(['model']).agg(['mean', 'std'])
agg_df

                        seed             test set size           BLEU             ROUGE-1             ROUGE-2             ROUGE-L              METEOR             SARI-BP                SARI            CHRF-tgt            CHRF-src           intraDIST-1           intraDIST-2           interDIST-1           interDIST-2           Self-BLEU               rep-r               rep-w           seq-rep-n           paraphrase_reps     src-tgt sts           domain acc     rating acc           source acc       hyp lens               Uniq
                        mean         std          mean  std      mean       std      mean       std      mean       std      mean       std      mean       std      mean       std      mean       std      mean       std      mean       std        mean       std        mean       std        mean       std        mean       std      mean       std      mean       std      mean       std      mean       std            mean std        mean       std       mean std       mean       std       mean std       mean       std     mean         std
model
baseline          342.333333  556.961698         24736  0.0  0.113600  0.001453  0.414000  0.001000  0.170667  0.000577  0.309000  0.001000  0.311000  0.001000  0.304333  0.003408  0.441967  0.000379  0.304667  0.002517  0.158667  0.002082    0.768400  0.001819    0.977967  0.000493    0.004900  0.000100    0.019533  0.000451  0.246000  0.046189  0.081800  0.001997  0.138400  0.000889  0.065167  0.000551             NaN NaN    0.433867  0.003134        NaN NaN        NaN       NaN        NaN NaN  59.389333  0.946391   7124.0  183.847763
filt_freq_distro  342.333333  556.961698         24736  0.0  0.118567  0.002650  0.395333  0.003055  0.148000  0.002646  0.281000  0.003606  0.322667  0.003512  0.368200  0.003487  0.437167  0.001266  0.336000  0.002000  0.206333  0.001528    0.743267  0.004446    0.972600  0.000700    0.005833  0.000058    0.026267  0.000208  0.153667  0.013214  0.101267  0.002686  0.125200  0.002400  0.072400  0.001253             NaN NaN    0.483200  0.004000        NaN NaN        NaN       NaN        NaN NaN  82.365167  0.718423  11871.0   66.468037
filt_gen_sent     342.333333  556.961698         24736  0.0  0.113133  0.000451  0.398000  0.002646  0.149333  0.002082  0.285000  0.002646  0.316000  0.001000  0.355500  0.001735  0.435833  0.000643  0.325333  0.001528  0.202000  0.004359    0.734600  0.002666    0.969633  0.000814    0.006367  0.000058    0.029433  0.000862  0.131133  0.036256  0.110833  0.003004  0.135400  0.000721  0.075433  0.000850             NaN NaN    0.480500  0.003342        NaN NaN        NaN       NaN        NaN NaN  75.687667  1.687504  11894.0  482.246825
filt_tgt_ppl      342.333333  556.961698         24736  0.0  0.115333  0.001250  0.403000  0.001000  0.151333  0.001528  0.288333  0.001528  0.319667  0.000577  0.355133  0.002363  0.436633  0.000252  0.326333  0.002082  0.210000  0.003606    0.745067  0.002517    0.973033  0.000681    0.007333  0.000153    0.037133  0.001250  0.042367  0.009069  0.099767  0.002228  0.129133  0.001250  0.071933  0.000751             NaN NaN    0.507500  0.003568        NaN NaN     0.9685  0.002121        NaN NaN  73.817133  1.374777  13274.5  440.527525

In [5]:
# get max and min std values for each metric
stds = agg_df.loc[:, (slice(None), 'std')]
stds

                        seed test set size      BLEU   ROUGE-1   ROUGE-2   ROUGE-L    METEOR   SARI-BP      SARI  CHRF-tgt  CHRF-src intraDIST-1 intraDIST-2 interDIST-1 interDIST-2 Self-BLEU     rep-r     rep-w seq-rep-n paraphrase_reps src-tgt sts domain acc rating acc source acc  hyp lens        Uniq
                         std           std       std       std       std       std       std       std       std       std       std         std         std         std         std       std       std       std       std             std         std        std        std        std       std         std
model
baseline          556.961698           0.0  0.001453  0.001000  0.000577  0.001000  0.001000  0.003408  0.000379  0.002517  0.002082    0.001819    0.000493    0.000100    0.000451  0.046189  0.001997  0.000889  0.000551             NaN    0.003134        NaN        NaN        NaN  0.946391  183.847763
filt_freq_distro  556.961698           0.0  0.002650  0.003055  0.002646  0.003606  0.003512  0.003487  0.001266  0.002000  0.001528    0.004446    0.000700    0.000058    0.000208  0.013214  0.002686  0.002400  0.001253             NaN    0.004000        NaN        NaN        NaN  0.718423   66.468037
filt_gen_sent     556.961698           0.0  0.000451  0.002646  0.002082  0.002646  0.001000  0.001735  0.000643  0.001528  0.004359    0.002666    0.000814    0.000058    0.000862  0.036256  0.003004  0.000721  0.000850             NaN    0.003342        NaN        NaN        NaN  1.687504  482.246825
filt_tgt_ppl      556.961698           0.0  0.001250  0.001000  0.001528  0.001528  0.000577  0.002363  0.000252  0.002082  0.003606    0.002517    0.000681    0.000153    0.001250  0.009069  0.002228  0.001250  0.000751             NaN    0.003568        NaN   0.002121        NaN  1.374777  440.527525

In [16]:
app_df = load_data(Path('../../models/apps'))
app_df.to_csv('app_results.csv', index=False)

baseline 0
3
filt_tgt_ppl_13.5_200 0
3
filt_tgt_ppl_23_200 0
3
filt_tgt_ppl_3.0_200 0
3
filt_tgt_ppl_8.5_200 0
3
ground_truth 0
3